name: analyze-mint-transactions
channels:
  - conda-forge
dependencies:
  - ipython
  - jupyter
  - lunchable
  - matplotlib
  - notebook
  - numpy
  - pandas
  - python
  - seaborn
  - black
  - flake8
